"""
Configuration handling for Velociraptor MCP server.

Supports two authentication methods:
1. Config file path (VELOCIRAPTOR_CONFIG_PATH)
2. Environment variables for individual components
"""

import os
import yaml
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


@dataclass
class VelociraptorConfig:
    """Configuration for connecting to Velociraptor server."""

    api_url: str
    client_cert: str
    client_key: str
    ca_cert: str
    api_connection_string: Optional[str] = None

    @classmethod
    def from_config_file(cls, config_path: str) -> "VelociraptorConfig":
        """Load configuration from a Velociraptor API client config file.

        The config file is generated by:
        velociraptor --config server.config.yaml config api_client --name <user> api_client.yaml
        """
        path = Path(config_path)
        if not path.exists():
            raise FileNotFoundError(f"Config file not found: {config_path}")

        with open(path, "r") as f:
            config = yaml.safe_load(f)

        # Extract the API connection string if present (newer format)
        api_connection_string = config.get("api_connection_string")

        # Extract certificate data
        ca_cert = config.get("ca_certificate", "")
        client_cert = config.get("client_cert", "")
        client_key = config.get("client_private_key", "")

        # Get API URL
        api_url = config.get("api_url", "")
        if not api_url and api_connection_string:
            # Parse from connection string if needed
            api_url = api_connection_string

        return cls(
            api_url=api_url,
            client_cert=client_cert,
            client_key=client_key,
            ca_cert=ca_cert,
            api_connection_string=api_connection_string,
        )

    @classmethod
    def from_env(cls) -> "VelociraptorConfig":
        """Load configuration from environment variables.

        Environment variables:
        - VELOCIRAPTOR_API_URL: The API endpoint URL
        - VELOCIRAPTOR_CLIENT_CERT: Path to client certificate or PEM content
        - VELOCIRAPTOR_CLIENT_KEY: Path to client private key or PEM content
        - VELOCIRAPTOR_CA_CERT: Path to CA certificate or PEM content
        """
        api_url = os.environ.get("VELOCIRAPTOR_API_URL", "")

        # Handle cert/key - can be path or content
        client_cert = cls._load_cert_or_key(
            os.environ.get("VELOCIRAPTOR_CLIENT_CERT", "")
        )
        client_key = cls._load_cert_or_key(
            os.environ.get("VELOCIRAPTOR_CLIENT_KEY", "")
        )
        ca_cert = cls._load_cert_or_key(
            os.environ.get("VELOCIRAPTOR_CA_CERT", "")
        )

        return cls(
            api_url=api_url,
            client_cert=client_cert,
            client_key=client_key,
            ca_cert=ca_cert,
        )

    @staticmethod
    def _load_cert_or_key(value: str) -> str:
        """Load certificate or key from path or return as content."""
        if not value:
            return ""

        # Check if it looks like a file path
        if os.path.exists(value):
            with open(value, "r") as f:
                return f.read()

        # Otherwise treat as PEM content
        return value

    def validate(self) -> None:
        """Validate that required configuration is present."""
        errors = []

        if not self.api_url:
            errors.append("API URL is required")
        if not self.client_cert:
            errors.append("Client certificate is required")
        if not self.client_key:
            errors.append("Client private key is required")
        if not self.ca_cert:
            errors.append("CA certificate is required")

        if errors:
            raise ValueError(f"Invalid configuration: {'; '.join(errors)}")


def load_config() -> VelociraptorConfig:
    """Load Velociraptor configuration from available sources.

    Priority:
    1. VELOCIRAPTOR_CONFIG_PATH environment variable (config file)
    2. Individual environment variables

    Returns:
        VelociraptorConfig: The loaded configuration

    Raises:
        ValueError: If no valid configuration is found
    """
    # Try config file first
    config_path = os.environ.get("VELOCIRAPTOR_CONFIG_PATH")
    if config_path:
        config = VelociraptorConfig.from_config_file(config_path)
        config.validate()
        return config

    # Try environment variables
    config = VelociraptorConfig.from_env()

    # Check if we have any configuration
    if config.api_url or config.client_cert:
        config.validate()
        return config

    raise ValueError(
        "No Velociraptor configuration found. "
        "Set VELOCIRAPTOR_CONFIG_PATH to a config file path, "
        "or set VELOCIRAPTOR_API_URL, VELOCIRAPTOR_CLIENT_CERT, "
        "VELOCIRAPTOR_CLIENT_KEY, and VELOCIRAPTOR_CA_CERT environment variables."
    )
